title: Products
modelClass: Dondo\SystemManagement\Models\Product
list: $/dondo/systemmanagement/models/product/columns.yaml
recordUrl: 'dondo/systemmanagement/products/preview/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
